/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing ApiAddTaskViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiAddTaskViewModelTests
    {
        // TODO uncomment below to declare an instance variable for ApiAddTaskViewModel
        //private ApiAddTaskViewModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiAddTaskViewModel
            //instance = new ApiAddTaskViewModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiAddTaskViewModel
        /// </summary>
        [Test]
        public void ApiAddTaskViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiAddTaskViewModel
            //Assert.IsInstanceOfType<ApiAddTaskViewModel> (instance, "variable 'instance' is a ApiAddTaskViewModel");
        }


        /// <summary>
        /// Test the property 'TaskTitle'
        /// </summary>
        [Test]
        public void TaskTitleTest()
        {
            // TODO unit test for the property 'TaskTitle'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EstimateWork'
        /// </summary>
        [Test]
        public void EstimateWorkTest()
        {
            // TODO unit test for the property 'EstimateWork'
        }
        /// <summary>
        /// Test the property 'TaskCategoryId'
        /// </summary>
        [Test]
        public void TaskCategoryIdTest()
        {
            // TODO unit test for the property 'TaskCategoryId'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
