/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing ApiProjectModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiProjectModelTests
    {
        // TODO uncomment below to declare an instance variable for ApiProjectModel
        //private ApiProjectModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiProjectModel
            //instance = new ApiProjectModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiProjectModel
        /// </summary>
        [Test]
        public void ApiProjectModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiProjectModel
            //Assert.IsInstanceOfType<ApiProjectModel> (instance, "variable 'instance' is a ApiProjectModel");
        }


        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'ProjectTitle'
        /// </summary>
        [Test]
        public void ProjectTitleTest()
        {
            // TODO unit test for the property 'ProjectTitle'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusText'
        /// </summary>
        [Test]
        public void StatusTextTest()
        {
            // TODO unit test for the property 'StatusText'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'OwnerTitle'
        /// </summary>
        [Test]
        public void OwnerTitleTest()
        {
            // TODO unit test for the property 'OwnerTitle'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ContractTitle'
        /// </summary>
        [Test]
        public void ContractTitleTest()
        {
            // TODO unit test for the property 'ContractTitle'
        }
        /// <summary>
        /// Test the property 'CustomerTitle'
        /// </summary>
        [Test]
        public void CustomerTitleTest()
        {
            // TODO unit test for the property 'CustomerTitle'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'ContractId'
        /// </summary>
        [Test]
        public void ContractIdTest()
        {
            // TODO unit test for the property 'ContractId'
        }
        /// <summary>
        /// Test the property 'FilesCount'
        /// </summary>
        [Test]
        public void FilesCountTest()
        {
            // TODO unit test for the property 'FilesCount'
        }

    }

}
