/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing ApiTaskModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiTaskModelTests
    {
        // TODO uncomment below to declare an instance variable for ApiTaskModel
        //private ApiTaskModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiTaskModel
            //instance = new ApiTaskModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiTaskModel
        /// </summary>
        [Test]
        public void ApiTaskModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiTaskModel
            //Assert.IsInstanceOfType<ApiTaskModel> (instance, "variable 'instance' is a ApiTaskModel");
        }


        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Test]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'TaskTitle'
        /// </summary>
        [Test]
        public void TaskTitleTest()
        {
            // TODO unit test for the property 'TaskTitle'
        }
        /// <summary>
        /// Test the property 'StatusValue'
        /// </summary>
        [Test]
        public void StatusValueTest()
        {
            // TODO unit test for the property 'StatusValue'
        }
        /// <summary>
        /// Test the property 'StatusText'
        /// </summary>
        [Test]
        public void StatusTextTest()
        {
            // TODO unit test for the property 'StatusText'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'CreationDateString'
        /// </summary>
        [Test]
        public void CreationDateStringTest()
        {
            // TODO unit test for the property 'CreationDateString'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'DueDateString'
        /// </summary>
        [Test]
        public void DueDateStringTest()
        {
            // TODO unit test for the property 'DueDateString'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'StartDateString'
        /// </summary>
        [Test]
        public void StartDateStringTest()
        {
            // TODO unit test for the property 'StartDateString'
        }
        /// <summary>
        /// Test the property 'EstimateWork'
        /// </summary>
        [Test]
        public void EstimateWorkTest()
        {
            // TODO unit test for the property 'EstimateWork'
        }
        /// <summary>
        /// Test the property 'TaskCategoryTitle'
        /// </summary>
        [Test]
        public void TaskCategoryTitleTest()
        {
            // TODO unit test for the property 'TaskCategoryTitle'
        }
        /// <summary>
        /// Test the property 'ProjectTitle'
        /// </summary>
        [Test]
        public void ProjectTitleTest()
        {
            // TODO unit test for the property 'ProjectTitle'
        }
        /// <summary>
        /// Test the property 'TaskCategoryId'
        /// </summary>
        [Test]
        public void TaskCategoryIdTest()
        {
            // TODO unit test for the property 'TaskCategoryId'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'PercentCompleted'
        /// </summary>
        [Test]
        public void PercentCompletedTest()
        {
            // TODO unit test for the property 'PercentCompleted'
        }
        /// <summary>
        /// Test the property 'EstimateWorkSecondary'
        /// </summary>
        [Test]
        public void EstimateWorkSecondaryTest()
        {
            // TODO unit test for the property 'EstimateWorkSecondary'
        }
        /// <summary>
        /// Test the property 'PlannedPercentCompleted'
        /// </summary>
        [Test]
        public void PlannedPercentCompletedTest()
        {
            // TODO unit test for the property 'PlannedPercentCompleted'
        }
        /// <summary>
        /// Test the property 'FilesCount'
        /// </summary>
        [Test]
        public void FilesCountTest()
        {
            // TODO unit test for the property 'FilesCount'
        }
        /// <summary>
        /// Test the property 'CommentsCount'
        /// </summary>
        [Test]
        public void CommentsCountTest()
        {
            // TODO unit test for the property 'CommentsCount'
        }

    }

}
