/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing ApiUserModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiUserModelTests
    {
        // TODO uncomment below to declare an instance variable for ApiUserModel
        //private ApiUserModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiUserModel
            //instance = new ApiUserModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiUserModel
        /// </summary>
        [Test]
        public void ApiUserModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiUserModel
            //Assert.IsInstanceOfType<ApiUserModel> (instance, "variable 'instance' is a ApiUserModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'PersonCode'
        /// </summary>
        [Test]
        public void PersonCodeTest()
        {
            // TODO unit test for the property 'PersonCode'
        }

    }

}
