/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing PublicApiAuthenticateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicApiAuthenticateResultTests
    {
        // TODO uncomment below to declare an instance variable for PublicApiAuthenticateResult
        //private PublicApiAuthenticateResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicApiAuthenticateResult
            //instance = new PublicApiAuthenticateResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicApiAuthenticateResult
        /// </summary>
        [Test]
        public void PublicApiAuthenticateResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicApiAuthenticateResult
            //Assert.IsInstanceOfType<PublicApiAuthenticateResult> (instance, "variable 'instance' is a PublicApiAuthenticateResult");
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'UserInfo'
        /// </summary>
        [Test]
        public void UserInfoTest()
        {
            // TODO unit test for the property 'UserInfo'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'ErrorExtraData'
        /// </summary>
        [Test]
        public void ErrorExtraDataTest()
        {
            // TODO unit test for the property 'ErrorExtraData'
        }

    }

}
