/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BtApiClient.Api;
using BtApiClient.Model;
using BtApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing TaskCategoryViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskCategoryViewModelTests
    {
        // TODO uncomment below to declare an instance variable for TaskCategoryViewModel
        //private TaskCategoryViewModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskCategoryViewModel
            //instance = new TaskCategoryViewModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskCategoryViewModel
        /// </summary>
        [Test]
        public void TaskCategoryViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TaskCategoryViewModel
            //Assert.IsInstanceOfType<TaskCategoryViewModel> (instance, "variable 'instance' is a TaskCategoryViewModel");
        }


        /// <summary>
        /// Test the property 'TaskCategoryId'
        /// </summary>
        [Test]
        public void TaskCategoryIdTest()
        {
            // TODO unit test for the property 'TaskCategoryId'
        }
        /// <summary>
        /// Test the property 'TaskCategoryTitle'
        /// </summary>
        [Test]
        public void TaskCategoryTitleTest()
        {
            // TODO unit test for the property 'TaskCategoryTitle'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'ProjectTitle'
        /// </summary>
        [Test]
        public void ProjectTitleTest()
        {
            // TODO unit test for the property 'ProjectTitle'
        }

    }

}
