/* 
 * behTIME
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using BtApiClient.Client;
using BtApiClient.Api;
using BtApiClient.Model;

namespace BtApiClient.Test
{
    /// <summary>
    ///  Class for testing PublicApiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PublicApiApiTests
    {
        private PublicApiApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PublicApiApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicApiApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PublicApiApi
            //Assert.IsInstanceOfType(typeof(PublicApiApi), instance, "instance is a PublicApiApi");
        }

        
        /// <summary>
        /// Test PublicApiAddTask
        /// </summary>
        [Test]
        public void PublicApiAddTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //ApiAddTaskViewModel taskData = null;
            //string usersAssigned = null;
            //var response = instance.PublicApiAddTask(token, taskData, usersAssigned);
            //Assert.IsInstanceOf<ApiSingleResultApiTaskModel> (response, "response is ApiSingleResultApiTaskModel");
        }
        
        /// <summary>
        /// Test PublicApiAuthenticate
        /// </summary>
        [Test]
        public void PublicApiAuthenticateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string password = null;
            //Object clientInfo = null;
            //string clientLanguage = null;
            //string oldToken = null;
            //var response = instance.PublicApiAuthenticate(username, password, clientInfo, clientLanguage, oldToken);
            //Assert.IsInstanceOf<PublicApiAuthenticateResult> (response, "response is PublicApiAuthenticateResult");
        }
        
        /// <summary>
        /// Test PublicApiGetProjectTasks
        /// </summary>
        [Test]
        public void PublicApiGetProjectTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //long? projectId = null;
            //string searchTitle = null;
            //var response = instance.PublicApiGetProjectTasks(token, projectId, searchTitle);
            //Assert.IsInstanceOf<ApiListResultApiTaskModel> (response, "response is ApiListResultApiTaskModel");
        }
        
        /// <summary>
        /// Test PublicApiGetProjects
        /// </summary>
        [Test]
        public void PublicApiGetProjectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //int? startIndex = null;
            //int? pageSize = null;
            //string searchTitle = null;
            //bool? onlyActive = null;
            //var response = instance.PublicApiGetProjects(token, startIndex, pageSize, searchTitle, onlyActive);
            //Assert.IsInstanceOf<ApiListResultApiProjectModel> (response, "response is ApiListResultApiProjectModel");
        }
        
        /// <summary>
        /// Test PublicApiGetTaskCategories
        /// </summary>
        [Test]
        public void PublicApiGetTaskCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //int? startIndex = null;
            //int? pageSize = null;
            //string searchTitle = null;
            //long? projectId = null;
            //var response = instance.PublicApiGetTaskCategories(token, startIndex, pageSize, searchTitle, projectId);
            //Assert.IsInstanceOf<ApiListResultTaskCategoryViewModel> (response, "response is ApiListResultTaskCategoryViewModel");
        }
        
        /// <summary>
        /// Test PublicApiGetUsers
        /// </summary>
        [Test]
        public void PublicApiGetUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //int? startIndex = null;
            //int? pageSize = null;
            //string searchTitle = null;
            //var response = instance.PublicApiGetUsers(token, startIndex, pageSize, searchTitle);
            //Assert.IsInstanceOf<ApiListResultApiUserModel> (response, "response is ApiListResultApiUserModel");
        }
        
    }

}
